name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      ENABLE_COSTLY_TESTS: 1

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: |
          poetry install --with dev

      - name: Run Tests (with Coverage)
        run: |
          poetry run pytest --cov=concurrent_openai --cov-report=xml
  
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: marianstefi20/concurrent-openai

  release:
    needs: [test]
    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}
        cancel-in-progress: true
    
    permissions:
        contents: write
        id-token: write

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Install Poetry
          uses: snok/install-poetry@v1
        
        - name: Install dependencies
          run: |
            poetry install

        - name: Release
          id: release
          uses: python-semantic-release/python-semantic-release@v9.15.2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}

        - name: Build package
          run: |
            poetry build
            
        - name: Publish to PyPI
          uses: pypa/gh-action-pypi-publish@v1.12.3
          if: steps.release.outputs.released == 'true'
